from prometheus_client import Counter, Histogram, Gauge

# ---------------------------------------------------------
# HTTP metrics
# ---------------------------------------------------------

HTTP_REQUESTS = Counter(
    "http_requests_total",
    "Total number of HTTP requests",
    ["method", "endpoint", "status"],
)

HTTP_REQUEST_LATENCY = Histogram(
    "http_request_latency_seconds",
    "HTTP request latency in seconds",
    ["method", "endpoint"],
    buckets=(
        0.01,
        0.025,
        0.05,
        0.1,
        0.25,
        0.5,
        1.0,
        2.0,
        5.0,
        10.0,
    ),
)


# ---------------------------------------------------------
# RAG metrics
# ---------------------------------------------------------

RETRIEVAL_REQUESTS = Counter(
    "rag_retrieval_requests_total",
    "Total number of RAG retrieval requests",
)

RETRIEVAL_LATENCY = Histogram(
    "rag_retrieval_latency_seconds",
    "RAG retrieval latency in seconds",
    buckets=(
        0.005,
        0.01,
        0.025,
        0.05,
        0.1,
        0.25,
        0.5,
        1.0,
    ),
)

RETRIEVED_DOCUMENTS = Histogram(
    "rag_retrieved_documents",
    "Number of documents returned by retrieval",
    buckets=(1, 2, 3, 5, 10, 20),
)


# ---------------------------------------------------------
# LLM metrics
# ---------------------------------------------------------

LLM_REQUESTS = Counter(
    "llm_requests_total",
    "Total number of LLM requests",
    ["model"],
)

LLM_ERRORS = Counter(
    "llm_errors_total",
    "Total number of LLM errors",
    ["model"],
)

LLM_LATENCY = Histogram(
    "llm_latency_seconds",
    "LLM inference latency in seconds",
    ["model"],
    buckets=(
        0.05,
        0.1,
        0.25,
        0.5,
        1.0,
        2.0,
        5.0,
        10.0,
        30.0,
    ),
)


# ---------------------------------------------------------
# Cache metrics
# ---------------------------------------------------------

CACHE_REQUESTS = Counter(
    "cache_requests_total",
    "Total number of cache requests",
    ["result"],
)

CACHE_LATENCY = Histogram(
    "cache_operation_latency_seconds",
    "Latency of Redis cache operations",
    ["operation"],
)

CACHE_ERRORS = Counter(
    "cache_errors_total",
    "Number of failed Redis cache operations",
    ["operation"],
)


# ---------------------------------------------------------
# Token metrics
# ---------------------------------------------------------

LLM_INPUT_TOKENS = Counter(
    "llm_input_tokens_total",
    "Total input tokens sent to LLM",
    ["model"],
)

LLM_OUTPUT_TOKENS = Counter(
    "llm_output_tokens_total",
    "Total output tokens generated by LLM",
    ["model"],
)